WebAuthAppItra/Models/ErrorViewModel.cs
namespace WebAuthAppItra.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAuthAppItra/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using WebAuthAppItra.Data;

namespace WebAuthAppItra.Models
{
    public class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new WebAuthAppItraContext(
                serviceProvider.GetRequiredService<DbContextOptions<WebAuthAppItraContext>>()))
            {
                if (context.User.Any())
                {
                    return;
                }

                context.User.AddRange(
                    new User
                    {
                        Name = "Dima",
                        Email = "abc@mail.ru",
                        Password = "password",
                        //UserName = "Xxx",
                        RegistrationDate = DateTime.Now,
                        LastLoginTime = DateTime.Now,
                        IsBlocked = false,
                        IsChecked = false
                    },

                    new User
                    {
                        Name = "Andrey",
                        Email = "andrey@mail.ru",
                        Password = "password",
                        //UserName= "username",
                        RegistrationDate = DateTime.Now,
                        LastLoginTime = DateTime.Now,
                        IsBlocked = false,
                        IsChecked = false
                    }

                    );;
                context.SaveChanges();
            }
        }
    }
}

WebAuthAppItra/Models/User.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebAuthAppItra.Models
{
    public class User
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        
        // [DataType(DataType.Date)]
        public DateTime RegistrationDate { get; set; }
        public DateTime LastLoginTime { get; set;}
        public bool IsBlocked { get; set; }

        //[(DisplayValue = false)]
        public bool IsChecked { get; set; }
    }
}

WebAuthAppItra/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAuthAppItra.Data;
using WebAuthAppItra.Models;

namespace WebAuthAppItra.Controllers
{
    public class UsersController : Controller
    {
        private readonly WebAuthAppItraContext _context;

        private static string _userId = "empty";

        public UsersController(WebAuthAppItraContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["CurrentUser"] = _userId;
            return View(await _context.User.ToListAsync());
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost, ActionName("Login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User user)
        {
            var existedUser = await _context.User.FirstOrDefaultAsync(
                u => u.Email == user.Email && u.Password == user.Password);
            if (existedUser != null && !existedUser.IsBlocked)
            {
                existedUser.LastLoginTime = DateTime.Now;
                _context.User.Update(existedUser);
                _context.SaveChanges();
                _userId = existedUser.Id.ToString();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Message"] = "User not found or blocked";
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Password,RegistrationDate,LastLoginTime,IsBlocked")] User user)
        {
            
            if (_context.User.FirstOrDefault(u => u.Email == user.Email) != null)
            {
                ViewData["Message"] = "Already registered";
                return View();
            }
            if (ModelState.IsValid)
            {
                user.RegistrationDate = DateTime.Now;
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            return View();
        }

        [HttpPost]
        public IActionResult Block(bool[] IsChecked)
        {
            var i = 0;
            bool IsCurrentUserBlocked = false;
            foreach (var item in _context.User)
            {
                if (IsChecked[i])
                {
                    item.IsBlocked = true;
                    if (item.Id == Int32.Parse(_userId))
                    {
                        IsCurrentUserBlocked = true;
                    }
                }
                i++;
            }
            _context.SaveChanges();
            return IsCurrentUserBlocked ? RedirectToAction(nameof(Login)) : RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Unblock(bool[] IsChecked)
        {
            var i = 0;
            foreach (var item in _context.User)
            {
                var x = IsChecked.Length;
                if (IsChecked[i] && item.IsBlocked)
                {
                    item.IsBlocked = false;
                }
                i++;

            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Remove(bool[] IsChecked)
        {
            var i = 0;
            bool IsCurrentUserBlocked = false;
            foreach (var item in _context.User)
            {
                if (IsChecked[i])
                {
                    _context.User.Remove(item);
                    if (item.Id == Int32.Parse(_userId))
                    {
                        IsCurrentUserBlocked = true;
                    }
                }
                i++;
            }
            _context.SaveChanges();
            return IsCurrentUserBlocked ? RedirectToAction(nameof(Login)) : RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return _context.User.Any(e => e.Id == id);
        }
    }
}

WebAuthAppItra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAuthAppItra</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAuthAppItra.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">WebAuthAppItra</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAuthAppItra
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAuthAppItra/Views/Users/Create.cshtml
@model WebAuthAppItra.Models.User

@{
    ViewData["Title"] = "Registration";
}

<h1>Registration</h1>
<p style="color:red;">@ViewData["Message"]</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
                <p style="color:blue">*You will be redirected to login page</p>
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAuthAppItra/Views/Users/Delete.cshtml
@model WebAuthAppItra.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLoginTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLoginTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBlocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBlocked)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAuthAppItra/Views/Users/Details.cshtml
@model WebAuthAppItra.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLoginTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLoginTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBlocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBlocked)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebAuthAppItra/Views/Users/Edit.cshtml
@model WebAuthAppItra.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationDate" class="control-label"></label>
                <input asp-for="RegistrationDate" class="form-control" />
                <span asp-validation-for="RegistrationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLoginTime" class="control-label"></label>
                <input asp-for="LastLoginTime" class="form-control" />
                <span asp-validation-for="LastLoginTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsBlocked" /> @Html.DisplayNameFor(model => model.IsBlocked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAuthAppItra/Views/Users/Index.cshtml
@model IEnumerable<WebAuthAppItra.Models.User>

@{
    ViewData["Title"] = "Index";
    
}
@{
    var i = 0;
}
<h1>Index</h1>

<body>
<form method="post">

<p>
            <button type="submit" asp-action="Block" name="BlockingButtons">Block</button>
            <button type="submit" asp-action="Unblock" name="BlockingButtons">Unblock</button>
            <button type="submit" asp-action="Remove" name="BlockingButtons">Remove</button>
</p>

<table class="table">
    <thead>
        <tr>
            <td>
                <input type="checkbox" id="headCheck"/>
                        <script>
                            var x = document.getElementById('headCheck');
                            var y = document.getElementsByClassName('checkbox');
                            console.log(y);
                            x.addEventListener('change', (event) => {                               
                                    for (let item of y) {
                                        item.toggleAttribute('value');
                                        console.log(item);
                                    }
                            })
                        </script>
            </td>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Password)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.RegistrationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastLoginTime)
            </th>
            <th>
                Status (is blocked)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
       
@foreach (var item in Model) {
        <tr>
            <td>
                <input type="checkbox" id="check" name="IsChecked[@i]" value="true" class="checkbox"/>
                <input type="hidden" name="IsChecked[@i]" value="false" class="checkbox" />
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastLoginTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsBlocked)
            </td>
        </tr>
        <!---@(i++)--->
}
    </tbody>
    
</table>
        
    
</form>
</body>

WebAuthAppItra/Views/Users/Login.cshtml
@model WebAuthAppItra.Models.User

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>
<p style="color:red;">@ViewData["Message"]</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Create">Sign Up</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}